### ISSUE TITLE
snptoolkit annotate 

### ISSUE THREAD

**Issue by Kelzor** [Amine-Namouchi/snpToolkit#2] opened 2021-02-17 21:31 UTC
When I run `snptoolkit annotate` the INDEL and SNP output directories are generated, but they are empty. snptoolkit doesn't report any errors, but the progress bar stays at 0%. I am using a vcf file generated by freebayes and genbank file downloaded directly from NCBI. What could be going wrong?

```
$ snptoolkit annotate -i snps.raw.vcf -g sequence.gb
[14:23:05] [INFO] [1 CPUs requested out of 8 detected on this machine]
[14:23:05] [INFO] [snpToolkit is filtering and annotating your SNPs]
  0%|                                                                                                           | 0/1 [00:00<?, ?it/s]
[14:23:08] [INFO] [snpToolkit output files will be located in folders snpToolkit_SNPs_output_2021-02-17_at_14.23.05 and snpToolkit_INDELS_output_2021-02-17_at_14.23.05]
  0%|                                                                                                           | 0/1 [00:02<?, ?it/s]
```

**Comment by Amine-Namouchi** [comment] 2021-03-04 22:12
Hi Kelly,
sorry for the late reply. I am suspecting that the problem is related to your sequence.gb file. Did you check that the gb file contains the nucleotide sequence of your reference at the end of it?

**Comment by Kelzor** [comment] 2021-03-09 18:53
Hi, Amine! No worries. Thanks for your help. I am really excited about your tool, and I hope I can get it to work. 

Yes, it does have the DNA sequence at the end. I downloaded it directly from the [NCBI genome assembly page](https://www.ncbi.nlm.nih.gov/genome/?term=mycobacterium%20tuberculosis). 

Included here is the part of the sequence.gb file as it transitions from gene information to DNA sequence:

```
                     /db_xref="GeneID:886248"
                     /translation="MIATPGLFAVLRARNRMRRSADFETTVKHGMRTVRSDMVVYWWR
                     GSGGGPRVGLIIAKSVGSAVERHRVARRLRHVAGSIVKELHPSDHVVIRALPSSRHVS
                     SARLEQQLRCGLRRAVELAGSDR"
     gene            complement(4410786..4410929)
                     /gene="rpmH"
                     /locus_tag="Rv3924c"
                     /db_xref="GeneID:886258"
     CDS             complement(4410786..4410929)
                     /gene="rpmH"
                     /locus_tag="Rv3924c"
                     /experiment="COORDINATES:Mass spectrometry[PMID:21969609]"
                     /inference="protein motif:PROSITE:PS00784"
                     /codon_start=1
                     /transl_table=11
                     /product="50S ribosomal protein L34"
                     /protein_id="NP_218441.1"
                     /db_xref="GeneID:886258"
                     /translation="MTKGKRTFQPNNRRRARVHGFRLRMRTRAGRSIVSSRRRKGRRT
                     LSA"
CONTIG      join(AL123456.3:1..4411532)
ORIGIN      
        1 ttgaccgatg accccggttc aggcttcacc acagtgtgga acgcggtcgt ctccgaactt
       61 aacggcgacc ctaaggttga cgacggaccc agcagtgatg ctaatctcag cgctccgctg
      121 acccctcagc aaagggcttg gctcaatctc gtccagccat tgaccatcgt cgaggggttt
      181 gctctgttat ccgtgccgag cagctttgtc caaaacgaaa tcgagcgcca tctgcgggcc
      241 ccgattaccg acgctctcag ccgccgactc ggacatcaga tccaactcgg ggtccgcatc
      301 gctccgccgg cgaccgacga agccgacgac actaccgtgc cgccttccga aaatcctgct
      361 accacatcgc cagacaccac aaccgacaac gacgagattg atgacagcgc tgcggcacgg
      421 ggcgataacc agcacagttg gccaagttac ttcaccgagc gcccgcacaa taccgattcc
      481 gctaccgctg gcgtaaccag ccttaaccgt cgctacacct ttgatacgtt cgttatcggc
      541 gcctccaacc ggttcgcgca cgccgccgcc ttggcgatcg cagaagcacc cgcccgcgct
      601 tacaaccccc tgttcatctg gggcgagtcc ggtctcggca agacacacct gctacacgcg
```


The reference sequence used for mapping has a different name than the sequence.gb accession (but they are the same length), so I thought that may be the problem. But changing the chromosome name in the snps.vcf file to match the locus and/or accession IDs of the sequence.gb did not solve the problem. Is the sequence.gb in the wrong format?

**Comment by Amine-Namouchi** [comment] 2021-03-14 20:31
Happy to help. Indeed, it's weird that you still have a problem after changing the names! to help you in a more efficient way, can you please send me by email, the Genbank file and one of your vcf files. If I have them it will be very easy for me for see the problem and help.
Amine

**Comment by Kelzor** [comment] 2021-03-17 18:18
I'm not sure what your best email address is, but here they are. 

[snptoolkit.zip](https://github.com/Amine-Namouchi/snpToolkit/files/6158712/snptoolkit.zip)

Thanks so much!

**Comment by Amine-Namouchi** [comment] 2021-03-19 10:06
great! the one in shown at the bottom when you type snptoolkit -h. I will check your data and get back to you

**Comment by Amine-Namouchi** [comment] 2021-03-22 15:20
Hi Kelly! 
I have updated snptoolkit to version 2.3.0 
please update snptoolkit using: pip install snptoolkit --upgrade --user
I have fixed a problem related to Freebayes output vcf files. It should work fine now. 
let me know if you are able to analyze your data with the new update without any problem.
Best

**Comment by Amine-Namouchi** [comment] 2021-04-06 20:21
Hi kelly, I will close this issue. If you still have any issues just open a new one.
Best,
Amine

**Closed as completed by Amine-Namouchi** 2021-04-06 20:21 UTC
